# Generated by Django 5.1.6 on 2025-03-06 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_teacher_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='slug',
        ),
    ]
